# .travis.yml for haystack

language: python

python:
  - "2.7"
#  - "3.4"

before_install:
# travis-ci use Ubuntu 12.04.5 LTS (Precise Pangolin) 64bit
# install snapshot version of libclang1 libclang-common-3.X-dev
  - sudo apt-add-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" --yes
  - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main"  --yes
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get update -qq
    # arrrh... http://docs.travis-ci.com/user/languages/python/.
    # system python package will not be used.
  - sudo apt-get -q install libclang1-3.7 --yes --force-yes
#permission denied  - sudo echo `echo "/usr/lib/llvm-3.7/lib/" >> /etc/ld.so.conf.d/llvm-dev.conf`
  - sudo ln -v -s /usr/lib/x86_64-linux-gnu/libclang-3.7.so.1 /usr/lib/x86_64-linux-gnu/libclang.so
  - sudo ldconfig  
# tests dependencies
  - pip -q install coveralls

install:
# install with requirements
  - python setup.py -q install

before_script:
# we need the libc6-dev i386 version too to build the tests., but after building all install deps
# we also need 
  - sudo apt-get -q install libc6-dev libc6-dev-i386 --yes --force-yes
# we also need the libgcc-dev packages  for "/usr/bin/ld: cannot find crtbegin.o: No such file or directory"
  - sudo apt-get -q install libgcc-4.8-dev --yes --force-yes
# we need stdc++ 32 bits too /usr/bin/ld: cannot find -lstdc++  
  - sudo apt-get -q install libstdc++6:i386 libstdc++-4.8-dev:i386 --yes --force-yes

script:
# build memory tests. Need root for memory dumps. sudo is called in Makefile
  - python setup.py preptests
# run tests. Need root for memory dumps tests.
#  - python setup.py test
# run coverage only on test, not on memory dumps.
#  - coverage run --source=haystack setup.py test

after_success:
  - which clang
  - clang --version
  - which gcc
  - gcc --version
  - dpkg -l
  coveralls

after_failure:
# debug versions
  - which clang
  - clang --version
  - which gcc
  - gcc --version
  - dpkg -l


# disable email notifications
notifications:
  email:
    on_success: never
    on_failure: never


