# .travis.yml for haystack

language: python

python:
  - "2.7"
#  - "3.4"


install:
# travis-ci use Ubuntu 12.04.5 LTS (Precise Pangolin) 64bit
# install gcc dev requirements
 - sudo apt-get install libc6-dev --yes --force-yes
# tests dependencies
#  - pip install nose
  - pip install -r requirements.txt
  - pip install coveralls

script:
# run tests
  - python setup.py test
  - coverage run --source=python-haystack setup.py test

after_success:
  coveralls

# disable email notifications
notifications:
  email:
    on_success: never
    on_failure: never


