# .travis.yml for haystack

language: python

python:
  - "2.7"
#  - "3.5"

# we are using pre-dumped tests files
# and not testing the dumping capacity of haystack.
# travis-ci does not support llvm 3.7 yet, so lets not put a bunch
# of dependencies due to ctypeslib2.
# this test will start from already existing ctypeslib2 generated files.
# system python package will not be used. http://docs.travis-ci.com/user/languages/python/.
# numpy is already installed
# we can use containers.

sudo: false

# install any dependencies required
install:
## we need coveralls
  - pip -q install coveralls
## install with requirements
  - pip install -r requirements.txt --use-mirrors

before_script:
# we also need the large test files (memory dumps)
  - mkdir -p test/dumps/putty
  - mkdir -p test/dumps/ssh
  - mkdir -p test/dumps/vol
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/putty.1.dump.zip
  - unzip -q putty.1.dump.zip
  - mv putty.1.dump test/dumps/putty/
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/putty.7124.dump.zip
  - unzip -q putty.7124.dump.zip
  - mv putty.7124.dump test/dumps/putty/
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/ssh.1.tgz
  - tar zxf ssh.1.tgz
  - mv ssh.1 test/dumps/ssh/
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/ssh.x64.6653.dump.tgz
  - tar zxf ssh.x64.6653.dump.tgz
  - mv ssh.x64.6653.dump test/dumps/ssh/
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/zeus.vmem.1668.dump.tgz
  - tar zxf zeus.vmem.1668.dump.tgz
  - mv zeus.vmem.1668.dump test/dumps/vol/
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/zeus.vmem.856.dump.tgz
  - tar zxf zeus.vmem.856.dump.tgz
  - mv zeus.vmem.856.dump test/dumps/vol/
# we need the simple memory tests.
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/src-daa9302c5098fd0c2bd66917ae920e8fdea45705.tgz
  - tar zxf src-daa9302c5098fd0c2bd66917ae920e8fdea45705.tgz -C test/


script:
# run tests. Need root for memory dumps tests.
#  - python setup.py test
  - coverage run --source=haystack setup.py test

after_success:
  - coveralls

after_failure:
  - coveralls
  - find

# disable email notifications
notifications:
  email:
    on_success: never
    on_failure: never


