# .travis.yml for haystack

language: python

python:
  - "2.7"
#  - "3.5"

sudo: false

# system python package will not be used. http://docs.travis-ci.com/user/languages/python/.
# numpy is already installed

#before_install:
## travis-ci use Ubuntu 12.04.5 LTS (Precise Pangolin) 64bit
## we dont need that and it gets upgraded for some reason
#  - sudo apt-get remove oracle-java7-installer
## install the snapshot version of libclang1 >= 3.7
#  - sudo apt-add-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" --yes
#  - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main"  --yes
#  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
#  - sudo apt-get update -qq
#  - sudo apt-get -qq install libclang1-3.8 --yes --force-yes
## permission denied  - sudo echo `echo "/usr/lib/llvm-3.8/lib/" >> /etc/ld.so.conf.d/llvm-dev.conf`
#  - sudo ln -v -s /usr/lib/x86_64-linux-gnu/libclang-3.8.so.1 /usr/lib/x86_64-linux-gnu/libclang.so
#  - sudo ldconfig

# install any dependencies required
# because our preptests runs and dumps simple memory dumps,
# we need sudo, and we need to have installed haystack for root.
install:
## we need coveralls
  - pip -q install coveralls
## install with requirements
#  - python setup.py install
## or try the develop way to use the git tree
  - pip install -r requirements.txt --use-mirrors
#  - python setup.py develop

before_script:
# we need the libc6-dev i386 version too to build the tests., but after building all install deps python
# we also need
#  - sudo apt-get -qq install libc6-dev libc6-dev-i386 --yes --force-yes
# we also need the libgcc-dev packages  for "/usr/bin/ld: cannot find crtbegin.o: No such file or directory"
#  - sudo apt-get -qq install libgcc-4.8-dev --yes --force-yes
# we need stdc++ 32 bits too /usr/bin/ld: cannot find -lstdc++
#  - sudo apt-get -qq install libstdc++6:i386 libstdc++-4.8-dev:i386 --yes --force-yes
## we dont need this as we dont build them anymore
#  - sudo apt-get -qq install libc6-dev libc6-dev-i386 libgcc-4.8-dev libstdc++6:i386 libstdc++-4.8-dev:i386 --yes --force-yes
# we also need the large test files (memory dumps)
  - mkdir -p test/dumps/putty
  - mkdir -p test/dumps/ssh
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/putty.1.dump.zip
  - unzip -q putty.1.dump.zip
  - mv putty.1.dump test/dumps/putty/
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/putty.7124.dump.zip
  - unzip -q putty.7124.dump.zip
  - mv putty.7124.dump test/dumps/putty/
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/ssh.1.tgz
  - tar zxf ssh.1.tgz
  - mv ssh.1 test/dumps/ssh/
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/ssh.x64.6653.dump.tgz
  - tar zxf ssh.x64.6653.dump.tgz
  - mv ssh.x64.6653.dump test/dumps/ssh/
# build memory tests.
# just uncompress the tgz contained in the LFS.
# the preps tests does not build the binaries on travis-ci anymore.
# no need for root. No need for install haystack.
#  - python setup.py preptests
  - wget https://dl.dropboxusercontent.com/u/10222931/HAYSTACK/src-20150808.tgz
  - tar zxf src-20150808.tgz
  - mv test/src test/src.old
  - mv src test/

script:
# run tests. Need root for memory dumps tests.
#  - python setup.py test
# run coverage only on test, not on memory dumps.
  - coverage run --source=haystack setup.py test
#   - python -m cProfile setup.py test
#  - python -m cProfile -o setup.profile setup.py test

after_success:
  - coveralls
  - python -c"import pstats; p = pstats.Stats('setup.profile'); p.sort_stats('cumtime'); p.print_stats()"

after_failure:
  - coveralls
# debug versions
  - python -c"import pstats; p = pstats.Stats('setup.profile'); p.sort_stats('cumtime'); p.print_stats()"
  - which clang
  - clang --version
  - which gcc
  - gcc --version
  - make -v
  - dpkg -l
  - find
  - cat /etc/sudoers

# disable email notifications
notifications:
  email:
    on_success: never
    on_failure: never


